---
- hosts: all
  gather_facts: no
  become: yes
  vars:
    username: naveen5758
    token: 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
    repo_name: sample_project

  tasks:
    - name: Checkout The Code From Github Using Ansible.
      git:
        repo: 'https://{{ token }}@github.com/{{ username }}/{{ repo_name }}.git'
        dest: /home/ansadmin/tomcat/

    - name: Installing the java code
      yum:
        name: https://corretto.aws/downloads/latest/amazon-corretto-11-x86-linux-jdk.rpm
        state: present
      with_items:
        - https://corretto.aws/downloads/latest/amazon-corretto-11-x86-linux-jdk.rpm
        - maven



    - name: Extract tomcat
      unarchive:
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz
        dest: /home/ansadmin/tomcat/
        remote_src: yes

    - name: renaming
      shell: |
        mv /home/ansadmin/tomcat/apache-tomcat-9.0.78 /home/ansadmin/tomcat/apache_tomcat
        chmod -R 777 /home/ansadmin/tomcat/apache_tomcat
        cp /home/ansadmin/project2/citibank/target/SampleWebApp.war /home/ansadmin/tomcat/apache_tomcat/webapps/
        sh /home/ansadmin/tomcat/apache_tomcat/bin/startup.sh
