---
- name: A Playbook to test Async and Poll
  hosts: all
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: wait for the service
      wait_for:
        timeout: 60

    - name: start the service
      service:
        name: httpd
        state: started

